In [1]:
!pip install transformers sentencepiece sacrebleu pandas tqdm

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Collecting sacrebleu
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Downloading sacrebleu-2.6.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 2.1 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Installing collected packages: portalocker, colorama, sacrebleu
Successfully installed colorama-0.4.6 portalocker-3.2.0 sacrebleu-2.6.0

In [7]:
from pathlib import Path
from google.colab import drive
import pickle
import re
import time
import gc

import torch
import pandas as pd
import sacrebleu
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

In [8]:
drive.mount('/content/drive', force_remount=True)

dataset_path = Path("/content/drive/MyDrive/diplom/dataset")

with open("/content/drive/MyDrive/diplom/whisper_results_segments.pkl", "rb") as f:
    whisper_results = pickle.load(f)

print("Загружено видео:", len(whisper_results))
print("Ключи первого элемента:", whisper_results[0].keys())
print("Папки датасета:", [p.name for p in dataset_path.iterdir()])

Mounted at /content/drive
Загружено видео: 15
Ключи первого элемента: dict_keys(['folder', 'video', 'audio', 'ref', 'raw_text', 'segments', 'asr_time_sec'])
Папки датасета: ['video1', 'video2', 'video3', 'video4', 'video5', 'video6', 'video7', 'video8', 'video9', 'video10', 'video11', 'video12', 'video13', 'video14', 'video15']

Поиск эталонных русских переводов

In [9]:
def strip_srt(text: str) -> str:
    lines = text.splitlines()
    clean_lines = []

    for line in lines:
        line = line.strip()

        if not line:
            continue

        if line.isdigit():
            continue

        if "-->" in line:
            continue

        clean_lines.append(line)

    return " ".join(clean_lines)


def find_reference_ru(folder_name):
    folder_path = dataset_path / folder_name

    candidates = []

    for pattern in [
        "*reference*ru*.txt",
        "*ref*ru*.txt",
        "*ru*.txt",
        "*reference*.srt",
        "*ref*.srt",
        "*ru*.srt",
    ]:
        candidates.extend(folder_path.glob(pattern))

    candidates = list(dict.fromkeys(candidates))

    if not candidates:
        return None, None

    ref_path = candidates[0]
    text = ref_path.read_text(encoding="utf-8")

    if ref_path.suffix.lower() == ".srt":
        text = strip_srt(text)

    return ref_path, text.strip()

In [10]:
references = {}

for item in whisper_results:
    folder = item["folder"]
    ref_path, ref_text = find_reference_ru(folder)

    if ref_text:
        references[folder] = ref_text
        print(folder, "->", ref_path.name)
    else:
        print("Не найден эталонный перевод:", folder)

print("Эталонных переводов найдено:", len(references))

video1 -> ru.srt
video10 -> ru.srt
video11 -> ru.srt
video12 -> ru.srt
video13 -> ru.srt
video14 -> ru.srt
video15 -> ru.srt
video2 -> ru.srt
video3 -> ru.srt
video4 -> ru.srt
video5 -> ru.srt
video6 -> ru.srt
video7 -> ru.srt
video8 -> ru.srt
video9 -> ru.srt
Эталонных переводов найдено: 15

Очистка текста

In [11]:
def clean_text_for_subs(text: str) -> str:
    text = re.sub(
        r"\b(\w+)([\s,]+\1\b)+",
        r"\1",
        text,
        flags=re.IGNORECASE,
    )

    fillers = r"\b(er|eh|hmm|mm-hmm|uh-huh|uh-uh|oh|ah|uh|huh|erm|um)\b[,\s]*"
    text = re.sub(fillers, " ", text, flags=re.IGNORECASE)

    text = re.sub(r"\s{2,}", " ", text).strip()

    return text

Общие функции для моделей

In [12]:
DEVICE = "cpu"


def get_model_size_info(model):
    params = sum(p.numel() for p in model.parameters())
    size_mb_fp32 = params * 4 / 1024 / 1024

    return {
        "params_mln": round(params / 1_000_000, 1),
        "approx_size_mb_fp32": round(size_mb_fp32, 1),
    }

Opus-MT

In [13]:
def translate_segments_opus(
    segments,
    tokenizer,
    model,
    batch_size=8,
    max_new_tokens=128,
):
    texts_en_seg = [
        clean_text_for_subs(seg["text"])
        for seg in segments
    ]

    translated = []

    for i in range(0, len(texts_en_seg), batch_size):
        clean_texts = [
            t if t.strip() else "."
            for t in texts_en_seg[i:i + batch_size]
        ]

        batch = tokenizer(
            clean_texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
        ).to(DEVICE)

        with torch.no_grad():
            generated = model.generate(
                **batch,
                max_new_tokens=max_new_tokens,
                num_beams=5,
                no_repeat_ngram_size=3,
            )

        decoded = tokenizer.batch_decode(
            generated,
            skip_special_tokens=True,
        )

        translated.extend([d.strip() for d in decoded])

        del batch, generated
        gc.collect()

    ru_segments = []

    for seg, text_ru in zip(segments, translated):
        ru_segments.append({
            "start": seg["start"],
            "end": seg["end"],
            "text": text_ru,
        })

    return ru_segments

NLLB-600M

In [14]:
def translate_segments_nllb(
    segments,
    tokenizer,
    model,
    batch_size=2,
    max_new_tokens=128,
    src_lang="eng_Latn",
    tgt_lang="rus_Cyrl",
):
    tokenizer.src_lang = src_lang
    forced_bos_token_id = tokenizer.convert_tokens_to_ids(tgt_lang)

    texts_en_seg = [
        clean_text_for_subs(seg["text"])
        for seg in segments
    ]

    translated = []

    for i in range(0, len(texts_en_seg), batch_size):
        clean_texts = [
            t if t.strip() else "."
            for t in texts_en_seg[i:i + batch_size]
        ]

        batch = tokenizer(
            clean_texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
        ).to(DEVICE)

        with torch.no_grad():
            generated = model.generate(
                **batch,
                max_new_tokens=max_new_tokens,
                num_beams=5,
                forced_bos_token_id=forced_bos_token_id,
            )

        decoded = tokenizer.batch_decode(
            generated,
            skip_special_tokens=True,
        )

        translated.extend([d.strip() for d in decoded])

        del batch, generated
        gc.collect()

    ru_segments = []

    for seg, text_ru in zip(segments, translated):
        ru_segments.append({
            "start": seg["start"],
            "end": seg["end"],
            "text": text_ru,
        })

    return ru_segments

Основная функция эксперимента

In [15]:
all_results = []
translations_by_model = {}


def run_translation_experiment_for_model(
    model_label,
    model_name,
    model_type,
    src_lang=None,
    tgt_lang=None,
):
    print("=" * 70)
    print("Загрузка модели:", model_label)
    print("=" * 70)

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(DEVICE)
    model.eval()

    size_info = get_model_size_info(model)

    model_translations = {}

    for idx, item in enumerate(tqdm(whisper_results), start=1):
        folder = item["folder"]
        segments = item["segments"]

        if folder not in references:
            continue

        print("\n" + "=" * 60)
        print(f"Видео {idx} из {len(whisper_results)}")
        print("Папка:", folder)
        print("Количество Whisper-сегментов:", len(segments))
        print("Запуск перевода...")

        start_time = time.time()

        if model_type == "opus":
            ru_segments = translate_segments_opus(
                segments=segments,
                tokenizer=tokenizer,
                model=model,
                batch_size=8,
                max_new_tokens=128,
            )

        elif model_type == "nllb":
            ru_segments = translate_segments_nllb(
                segments=segments,
                tokenizer=tokenizer,
                model=model,
                batch_size=2,
                max_new_tokens=128,
                src_lang=src_lang,
                tgt_lang=tgt_lang,
            )

        else:
            raise ValueError("Неизвестный тип модели")

        translation_time = time.time() - start_time

        print("Перевод завершён")
        print("Время перевода:", round(translation_time, 4), "сек")

        hypothesis = " ".join(seg["text"] for seg in ru_segments)
        reference = references[folder]

        bleu = sacrebleu.corpus_bleu(
            [hypothesis],
            [[reference]],
        ).score

        chrf = sacrebleu.corpus_chrf(
            [hypothesis],
            [[reference]],
        ).score

        print("BLEU:", round(bleu, 4))
        print("chrF:", round(chrf, 4))

        all_results.append({
            "folder": folder,
            "model": model_label,
            "BLEU": round(bleu, 4),
            "chrF": round(chrf, 4),
            "translation_time_sec": round(translation_time, 4),
            "num_whisper_segments": len(segments),
            "avg_time_per_segment_sec": round(
                translation_time / max(1, len(segments)),
                4,
            ),
            "params_mln": size_info["params_mln"],
            "approx_size_mb_fp32": size_info["approx_size_mb_fp32"],
        })

        model_translations[folder] = ru_segments

    translations_by_model[model_label] = model_translations

    del tokenizer
    del model
    gc.collect()

    print("Модель выгружена:", model_label)

Запуск Opus-MT

In [16]:
run_translation_experiment_for_model(
    model_label="Opus-MT",
    model_name="Helsinki-NLP/opus-mt-en-ru",
    model_type="opus",
)

======================================================================
Загрузка модели: Opus-MT
======================================================================

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
  0%|          | 0/15 [00:00<?, ?it/s]

============================================================
Видео 1 из 15
Папка: video1
Количество Whisper-сегментов: 198
Запуск перевода...

  7%|▋         | 1/15 [02:20<32:46, 140.48s/it]

Перевод завершён
Время перевода: 140.4312 сек
BLEU: 18.548
chrF: 61.0277

============================================================
Видео 2 из 15
Папка: video10
Количество Whisper-сегментов: 26
Запуск перевода...

 13%|█▎        | 2/15 [02:34<14:22, 66.34s/it]

Перевод завершён
Время перевода: 14.4284 сек
BLEU: 20.9017
chrF: 51.1045

============================================================
Видео 3 из 15
Папка: video11
Количество Whisper-сегментов: 37
Запуск перевода...

 20%|██        | 3/15 [03:31<12:23, 62.00s/it]

Перевод завершён
Время перевода: 56.8029 сек
BLEU: 24.181
chrF: 59.7375

============================================================
Видео 4 из 15
Папка: video12
Количество Whisper-сегментов: 10
Запуск перевода...

 27%|██▋       | 4/15 [03:36<07:13, 39.41s/it]

Перевод завершён
Время перевода: 4.7881 сек
BLEU: 31.557
chrF: 58.0663

============================================================
Видео 5 из 15
Папка: video13
Количество Whisper-сегментов: 18
Запуск перевода...

 33%|███▎      | 5/15 [03:52<05:10, 31.07s/it]

Перевод завершён
Время перевода: 16.2541 сек
BLEU: 15.3926
chrF: 47.4927

============================================================
Видео 6 из 15
Папка: video14
Количество Whisper-сегментов: 11
Запуск перевода...

 40%|████      | 6/15 [04:01<03:30, 23.42s/it]

Перевод завершён
Время перевода: 8.5626 сек
BLEU: 63.6665
chrF: 77.9741

============================================================
Видео 7 из 15
Папка: video15
Количество Whisper-сегментов: 18
Запуск перевода...

 47%|████▋     | 7/15 [04:11<02:31, 18.91s/it]

Перевод завершён
Время перевода: 9.6201 сек
BLEU: 21.6893
chrF: 56.085

============================================================
Видео 8 из 15
Папка: video2
Количество Whisper-сегментов: 111
Запуск перевода...

 53%|█████▎    | 8/15 [05:23<04:12, 36.02s/it]

Перевод завершён
Время перевода: 72.6471 сек
BLEU: 22.1687
chrF: 52.9626

============================================================
Видео 9 из 15
Папка: video3
Количество Whisper-сегментов: 308
Запуск перевода...

 60%|██████    | 9/15 [08:38<08:33, 85.66s/it]

Перевод завершён
Время перевода: 194.7406 сек
BLEU: 18.8544
chrF: 59.4241

============================================================
Видео 10 из 15
Папка: video4
Количество Whisper-сегментов: 165
Запуск перевода...

 67%|██████▋   | 10/15 [10:50<08:20, 100.02s/it]

Перевод завершён
Время перевода: 132.1057 сек
BLEU: 28.1562
chrF: 69.7027

============================================================
Видео 11 из 15
Папка: video5
Количество Whisper-сегментов: 282
Запуск перевода...

 73%|███████▎  | 11/15 [14:11<08:43, 130.78s/it]

Перевод завершён
Время перевода: 200.4534 сек
BLEU: 21.936
chrF: 62.4365

============================================================
Видео 12 из 15
Папка: video6
Количество Whisper-сегментов: 34
Запуск перевода...

 80%|████████  | 12/15 [14:26<04:46, 95.64s/it]

Перевод завершён
Время перевода: 15.2665 сек
BLEU: 19.6807
chrF: 53.2695

============================================================
Видео 13 из 15
Папка: video7
Количество Whisper-сегментов: 274
Запуск перевода...

 87%|████████▋ | 13/15 [17:43<04:12, 126.21s/it]

Перевод завершён
Время перевода: 196.405 сек
BLEU: 19.8802
chrF: 64.8692

============================================================
Видео 14 из 15
Папка: video8
Количество Whisper-сегментов: 56
Запуск перевода...

 93%|█████████▎| 14/15 [18:22<01:40, 100.16s/it]

Перевод завершён
Время перевода: 39.9457 сек
BLEU: 10.3237
chrF: 48.6441

============================================================
Видео 15 из 15
Папка: video9
Количество Whisper-сегментов: 824
Запуск перевода...

100%|██████████| 15/15 [24:49<00:00, 99.32s/it]

Перевод завершён
Время перевода: 386.6687 сек
BLEU: 19.7667
chrF: 62.7872

Модель выгружена: Opus-MT

Запуск NLLB-600M

In [17]:
run_translation_experiment_for_model(
    model_label="NLLB-600M",
    model_name="facebook/nllb-200-distilled-600M",
    model_type="nllb",
    src_lang="eng_Latn",
    tgt_lang="rus_Cyrl",
)

======================================================================
Загрузка модели: NLLB-600M
======================================================================

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/512 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

  0%|          | 0/15 [00:00<?, ?it/s]

============================================================
Видео 1 из 15
Папка: video1
Количество Whisper-сегментов: 198
Запуск перевода...

  7%|▋         | 1/15 [23:31<5:29:16, 1411.15s/it]

Перевод завершён
Время перевода: 1411.0632 сек
BLEU: 18.6578
chrF: 62.6929

============================================================
Видео 2 из 15
Папка: video10
Количество Whisper-сегментов: 26
Запуск перевода...

 13%|█▎        | 2/15 [25:22<2:20:07, 646.70s/it]

Перевод завершён
Время перевода: 111.5815 сек
BLEU: 18.3554
chrF: 48.7096

============================================================
Видео 3 из 15
Папка: video11
Количество Whisper-сегментов: 37
Запуск перевода...

 20%|██        | 3/15 [33:17<1:53:37, 568.10s/it]

Перевод завершён
Время перевода: 474.525 сек
BLEU: 26.8912
chrF: 61.5708

============================================================
Видео 4 из 15
Папка: video12
Количество Whisper-сегментов: 10
Запуск перевода...

 27%|██▋       | 4/15 [34:01<1:06:12, 361.10s/it]

Перевод завершён
Время перевода: 43.7563 сек
BLEU: 23.4303
chrF: 57.3098

============================================================
Видео 5 из 15
Папка: video13
Количество Whisper-сегментов: 18
Запуск перевода...

 33%|███▎      | 5/15 [38:01<52:55, 317.53s/it]

Перевод завершён
Время перевода: 240.2602 сек
BLEU: 5.1265
chrF: 38.9744

============================================================
Видео 6 из 15
Папка: video14
Количество Whisper-сегментов: 11
Запуск перевода...

 40%|████      | 6/15 [39:14<35:09, 234.41s/it]

Перевод завершён
Время перевода: 73.055 сек
BLEU: 31.1546
chrF: 60.743

============================================================
Видео 7 из 15
Папка: video15
Количество Whisper-сегментов: 18
Запуск перевода...

 47%|████▋     | 7/15 [40:26<24:10, 181.37s/it]

Перевод завершён
Время перевода: 72.1623 сек
BLEU: 26.9553
chrF: 60.6142

============================================================
Видео 8 из 15
Папка: video2
Количество Whisper-сегментов: 111
Запуск перевода...

 53%|█████▎    | 8/15 [50:04<35:53, 307.62s/it]

Перевод завершён
Время перевода: 577.9379 сек
BLEU: 21.1896
chrF: 53.4489

============================================================
Видео 9 из 15
Папка: video3
Количество Whisper-сегментов: 308
Запуск перевода...

 60%|██████    | 9/15 [1:20:32<1:18:17, 782.92s/it]

Перевод завершён
Время перевода: 1827.8733 сек
BLEU: 19.0901
chrF: 59.6456

============================================================
Видео 10 из 15
Папка: video4
Количество Whisper-сегментов: 165
Запуск перевода...

 67%|██████▋   | 10/15 [1:42:38<1:19:13, 950.61s/it]

Перевод завершён
Время перевода: 1325.9862 сек
BLEU: 29.426
chrF: 70.4833

============================================================
Видео 11 из 15
Папка: video5
Количество Whisper-сегментов: 282
Запуск перевода...

 73%|███████▎  | 11/15 [2:14:34<1:23:03, 1245.95s/it]

Перевод завершён
Время перевода: 1915.4642 сек
BLEU: 24.7107
chrF: 65.079

============================================================
Видео 12 из 15
Папка: video6
Количество Whisper-сегментов: 34
Запуск перевода...

 80%|████████  | 12/15 [2:17:14<45:46, 915.54s/it]

Перевод завершён
Время перевода: 159.8193 сек
BLEU: 21.6318
chrF: 51.8311

============================================================
Видео 13 из 15
Папка: video7
Количество Whisper-сегментов: 274
Запуск перевода...

 87%|████████▋ | 13/15 [2:53:19<43:08, 1294.22s/it]

Перевод завершён
Время перевода: 2165.4818 сек
BLEU: 19.2137
chrF: 65.4154

============================================================
Видео 14 из 15
Папка: video8
Количество Whisper-сегментов: 56
Запуск перевода...

 93%|█████████▎| 14/15 [3:00:29<17:13, 1033.10s/it]

Перевод завершён
Время перевода: 429.6915 сек
BLEU: 9.7073
chrF: 48.9354

============================================================
Видео 15 из 15
Папка: video9
Количество Whisper-сегментов: 824
Запуск перевода...
Перевод завершён
Время перевода: 3537.2542 сек

100%|██████████| 15/15 [3:59:26<00:00, 957.79s/it]

BLEU: 17.38
chrF: 60.7546

Модель выгружена: NLLB-600M

Результаты

In [18]:
results_df = pd.DataFrame(all_results)
results_df

,folder,model,BLEU,chrF,translation_time_sec,num_whisper_segments,avg_time_per_segment_sec,params_mln,approx_size_mb_fp32
0,video1,Opus-MT,18.5480,61.0277,140.4312,198,0.7092,140.7,536.7
1,video10,Opus-MT,20.9017,51.1045,14.4284,26,0.5549,140.7,536.7
2,video11,Opus-MT,24.1810,59.7375,56.8029,37,1.5352,140.7,536.7
3,video12,Opus-MT,31.5570,58.0663,4.7881,10,0.4788,140.7,536.7
4,video13,Opus-MT,15.3926,47.4927,16.2541,18,0.9030,140.7,536.7
5,video14,Opus-MT,63.6665,77.9741,8.5626,11,0.7784,140.7,536.7
6,video15,Opus-MT,21.6893,56.0850,9.6201,18,0.5344,140.7,536.7
7,video2,Opus-MT,22.1687,52.9626,72.6471,111,0.6545,140.7,536.7
8,video3,Opus-MT,18.8544,59.4241,194.7406,308,0.6323,140.7,536.7
9,video4,Opus-MT,28.1562,69.7027,132.1057,165,0.8006,140.7,536.7
10,video5,Opus-MT,21.9360,62.4365,200.4534,282,0.7108,140.7,536.7
11,video6,Opus-MT,19.6807,53.2695,15.2665,34,0.4490,140.7,536.7
12,video7,Opus-MT,19.8802,64.8692,196.4050,274,0.7168,140.7,536.7
13,video8,Opus-MT,10.3237,48.6441,39.9457,56,0.7133,140.7,536.7
14,video9,Opus-MT,19.7667,62.7872,386.6687,824,0.4693,140.7,536.7
15,video1,NLLB-600M,18.6578,62.6929,1411.0632,198,7.1266,1402.1,5348.7
16,video10,NLLB-600M,18.3554,48.7096,111.5815,26,4.2916,1402.1,5348.7
17,video11,NLLB-600M,26.8912,61.5708,474.5250,37,12.8250,1402.1,5348.7
18,video12,NLLB-600M,23.4303,57.3098,43.7563,10,4.3756,1402.1,5348.7
19,video13,NLLB-600M,5.1265,38.9744,240.2602,18,13.3478,1402.1,5348.7
20,video14,NLLB-600M,31.1546,60.7430,73.0550,11,6.6414,1402.1,5348.7
21,video15,NLLB-600M,26.9553,60.6142,72.1623,18,4.0090,1402.1,5348.7
22,video2,NLLB-600M,21.1896,53.4489,577.9379,111,5.2066,1402.1,5348.7
23,video3,NLLB-600M,19.0901,59.6456,1827.8733,308,5.9347,1402.1,5348.7
24,video4,NLLB-600M,29.4260,70.4833,1325.9862,165,8.0363,1402.1,5348.7
25,video5,NLLB-600M,24.7107,65.0790,1915.4642,282,6.7924,1402.1,5348.7
26,video6,NLLB-600M,21.6318,51.8311,159.8193,34,4.7006,1402.1,5348.7
27,video7,NLLB-600M,19.2137,65.4154,2165.4818,274,7.9032,1402.1,5348.7
28,video8,NLLB-600M,9.7073,48.9354,429.6915,56,7.6731,1402.1,5348.7
29,video9,NLLB-600M,17.3800,60.7546,3537.2542,824,4.2928,1402.1,5348.7

In [19]:
summary_df = (
    results_df
    .groupby("model", as_index=False)
    .agg({
        "BLEU": "mean",
        "chrF": "mean",
        "translation_time_sec": "mean",
        "avg_time_per_segment_sec": "mean",
        "params_mln": "first",
        "approx_size_mb_fp32": "first",
    })
    .sort_values(
        by=["chrF", "BLEU"],
        ascending=False,
    )
)

summary_df

,model,BLEU,chrF,translation_time_sec,avg_time_per_segment_sec,params_mln,approx_size_mb_fp32
1,Opus-MT,23.780180,59.038913,99.274673,0.709367,140.7,536.7
0,NLLB-600M,20.861353,57.747200,957.727460,6.877113,1402.1,5348.7

Сохранеие результатов

In [20]:
results_df.to_csv(
    "/content/drive/MyDrive/diplom/translation_model_results_correct.csv",
    index=False,
)

summary_df.to_csv(
    "/content/drive/MyDrive/diplom/translation_model_summary_correct.csv",
    index=False,
)